name: Skims Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Fluid Attacks Skims scan
        uses: docker://docker.io/fluidattacks/skims:latest
        with:
          args: skims scan .