name: Skims Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Fluid Attacks Skims scan
        run: |
          docker pull docker.io/fluidattacks/skims:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace docker.io/fluidattacks/skims:latest skims scan .